imagePullSecrets:
  enabled: false
  name: secretname

gate:
  acmeEmail: real-email@example.com
  tlsSecretName: host.example.com-tls
ingressBox:
  enabled: false  
  host: host.example.com
ingressMprove:
  enabled: false  
  isMaintenance: false  
  host: host.example.com
ingressMprovePlay:
  enabled: false  
  isMaintenance: false  
  host: host.example.com
ingressMproveDocs:
  enabled: false  
  host: host.example.com
ingressClickstack:
  enabled: false  
  host: host.example.com
ingressDatabasus:
  enabled: false  
  host: host.example.com

maintenance:
  image: ghcr.io/mprove-io/mprove-maintenance
  tag: 1.0.1
  name: maintenance
  replicas: 1
  affinity: {}
