{{- if .Values.ingressMproveDocs.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mprove-docs
  namespace: mprove-docs
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/tls-acme: "true" 
spec:
  ingressClassName: nginx
  tls: 
  - hosts:
    - {{ .Values.ingressMproveDocs.host }}
    secretName: {{ .Values.gate.tlsSecretName }}
  rules:
    - host: {{ .Values.ingressMproveDocs.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: docs
                port:
                  number: 3000
{{- end }} 