{{- if .Values.ingressClickstack.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: clickstack
  namespace: clickstack
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/tls-acme: "true" 
spec:
  ingressClassName: nginx
  tls: 
  - hosts:
    - {{ .Values.ingressClickstack.host }}
    secretName: {{ .Values.gate.tlsSecretName }}
  rules:
    - host: {{ .Values.ingressClickstack.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: clickstack-app
                port:
                  number: 3000
{{- end }} 