{{- if .Values.ingressMprovePlay.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mprove-play
  namespace: {{ ternary "default" "mprove-play" .Values.ingressMprovePlay.isMaintenance }}
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/tls-acme: "true" 
spec:
  ingressClassName: nginx
  tls: 
  - hosts:
    - {{ .Values.ingressMprovePlay.host }}
    secretName: {{ .Values.gate.tlsSecretName }}
  rules:
    - host: {{ .Values.ingressMprovePlay.host }}
      http:
        paths:
{{- if not .Values.ingressMprovePlay.isMaintenance }}
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 3000
{{- end }}
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ ternary "maintenance" "front" .Values.ingressMprovePlay.isMaintenance }}
                port:
                  number: 80
{{- end }} 